name: Generate Release
on:
  push:
    branches: main
env:
  GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Hakai Tests
        run: |
          python -m pip install --upgrade pip
          pip install git+https://HakaiInstitute:${{secrets.CI_TOKEN}}@github.com/HakaiInstitute/hakai-datasets-repo-standard-tests.git
      - name: Test with pytest
        run: |
          pytest --pyargs hakai_data_repo_tests

  release:
    runs-on: ubuntu-latest
    needs: tests

      PR_STATUS: ''
    steps:
      - uses: actions/checkout@v3
      - name: Set PR status as environment variable
        run: |
          echo 'PR_STATUS<<EOF' >> $GITHUB_ENV
          gh pr status >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create Pull Request
        if: ${{contains(env.PR_STATUS, 'There is no pull request associated with [main]')}}
        run: |
          gh pr create -B release -H main --title "Merge latest changes to main into release branch" --body-file ".github/workflows/release-body.md"
  merge:
    runs-on: ubuntu-latest
    needs: [tests, release]
    steps:
      - uses: actions/checkout@v3
      - name: Auto-merge pull requests
        run: gh pr merge --auto --merge
